### ISSUE TITLE
Add support for related tables

### ISSUE THREAD

**Issue by vchernetsky** [amigocloud/qgis-amigocloud-plugin#10]
AmigoCloud related tables need to be setup properly as relations between QGIS layers.

**Comment by DanielCaldwell** [comment]
Here is how to set it up manually in QGIS: 

![2018-01-18 - setup relationships for qgis](https://user-images.githubusercontent.com/2634673/35116601-dcdd14ba-fc40-11e7-9847-c17b721d1846.gif)

**Comment by arturocuya** [comment]
done
