### ISSUE TITLE
All values - including Numeric values - show as string type

### ISSUE THREAD

**Issue by rburhum** [amigocloud/qgis-amigocloud-plugin#4]
This is not allowing certain tools that do calculations to work properly.

**Comment by rburhum** [comment]
![screen shot 2017-10-17 at 6 58 08 am](https://user-images.githubusercontent.com/138918/31668986-907446ce-b308-11e7-9cad-180eb5652e8b.png)

**Comment by vchernetsky** [comment]
Fixed
