### ISSUE TITLE
Plugin doesn't work with nonascii charcaters. 

### ISSUE THREAD

**Issue by DanielCaldwell** [amigocloud/qgis-amigocloud-plugin#5]
I have an amigocloud dataset named: Evolución de gatas 

It fails on this line of code: https://github.com/amigocloud/qgis-amigocloud-plugin/blob/4c9f71738b9cd173df1a24c02f4f7aaf1d2b2e91/amigocloud_dialog.py#L98

It is setting the nameValue of the string of the item's text. Which should be the name of the dataset. Basically, we need to change the str function to the .encode or probably use the unicode function here:  The fix is described here: https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

Please change the str() method to support not ascii characters.

**Comment by vchernetsky** [comment]
This is fix. https://github.com/amigocloud/qgis-amigocloud-plugin/commit/3c65413d301d0393bc0a1438c08bc3d2fc1e5ecd
